# Generated by Django 5.2.3 on 2025-06-25 12:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=20, verbose_name="Номер дома")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("release_date", models.DateField(verbose_name="Дата выхода на рынок")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                        editable=False,
                        verbose_name="Уровень иерархии",
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="suppliers.contact", verbose_name="Контакты"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="suppliers", to="suppliers.product", verbose_name="Продукты"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplied_companies",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
    ]
